name = "daily-activities-tracker"
type = "javascript"
account_id = "504218a80a661abdb5f2ad7587001c99"
workers_dev = true
route = "minaqaldas.workers.dev"
zone_id = ""
main = "src/index.ts"
build = { command = "npm run build", cwd = "." }
env = { production = { routes = [{pattern = "daily-activities-tracker.pages.dev", zone_id = ""}] } }

[env.production]
routes = [{pattern = "your-domain.com/*"}]
